---
title: "Feedback MTurk Study"
author: "Dahler Battle, Guy El Khoury, Jane Hung, and Julian Tsang"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(foreign)
library(data.table)
library(knitr)
library(stargazer)
library(sandwich)
library(car)
library(dplyr)
library(ggmap)
library(revgeo)
library(AER)
library(ggplot2)
library(expss)

# clears workspace
rm(list = ls())

# round all numbers to 4 decimals
options(digits=4)
```

# Introduction

# Load Data
```{r, include=FALSE}
# d <- fread('Lungs_November+14,+2020_17.33.csv')
d <- fread('../check-valid-responses/data/qualtrics_results_final.csv')
#head(d)
```

```{r, include=FALSE}
d_respondents_only <-
  d[(Status == "IP Address") & (Finished == 'True'),]

# Remove these survey responses because they were from people who did the survey again. Double check that they are removed:
d_respondents_only <-
  d_respondents_only[!ResponseId %in% c(
    'R_1eRkKqfVAmkVzj2',
    'R_3FR03xu5zyOsRSU',
    'R_3HBQsMSMCgXPpKf',
    'R_dbzictBknL9jG3T'
  ), ]

# These WorkerId put in all 1 response (all Normal or all Pneumonia)
d_respondents_only <-
  d_respondents_only[!Q80 %in% c(
    "A119EX2L0DNN1B",
    "A12NQJV6TA5OWB",
    "A18WFPSLFV4FKY",
    "A1BUYK6LXYWMLL",
    "A1FHRZXSE7XNJ4",
    "A1GMYDH5MKN105",
    "A2GSZ3D2XXC533",
    "A2IGIOD74EPOEF",
    "A2J016DRTOBXWO",
    "A2NGFU82LMJ80X",
    "A32K1M0A36EAK5",
    "A371SNJNNUY9Z6",
    "A3BPENSX5EVJ2H",
    "A3EPIT2P3ISA3K",
    "A3NYIJYBHAJ74V",
    "AUFLTHQAXWLH1",
    "AVINXZZV3FNG7" ,
    "A1CD7O60QAQQRT",
    "A1CF1W8CP0DHB0",
    "A1PGY59BR6C5BX",
    "A1YSYI926BBOHW",
    "A1Z3GFH6MNSU46",
    "A211KGJ94WNFLN",
    "A26RPQDD0RQEHL",
    "A2BUHMLNE3LUU0",
    "A2J5BRQ88W745H",
    "A2XIHO2W7EEP32",
    "A3EZ0H07TSDAPW",
    "A3FLBC6LC5GJ3W",
    "A3QLKLIQW1B1FR",
    "A8F6JFG0WSELT",
    "A9K6IVBA0J1CX",
    "ADLZLGHKOAEE6",
    "AE7NJG0KOVZYJ" ,
    "AG5RF4UGQJ7A7" ,
    "AQ9Y6WD8O72ZC" ,
    "tuturtu"
  ), ]

# These people just gave alternating responses (Normal, Pneumonia, Normal,...,Pneumonia)

d_respondents_only <- d_respondents_only[!Q80 %in% c(
'A1W05TSPORJPXR'
,'A3SUWCLD1GEGM7'
,'A3A09JB9X1RBXW'
,'A7VQQEIBSM9IU'
,'A8DER1QY96C5X'
,'A1M8MNKK8H5ZGW'
,'A34D5D6PU193AR'
),]

#head(d_respondents_only)
```

```{r, include=FALSE}
#rename task phase questions
setnames(d_respondents_only,
         old = c('Q2', 'Q42'),
         new = c('Self_Reflect_Q1', 'Self_Reflect_Q2'))

setnames(d_respondents_only,
         old = c('Q69', 'Q89'),
         new = c('Control_Q1', 'Control_Q2'))

setnames(d_respondents_only,
         old = c('Q80', 'Q82', 'Q83', 'Q84', 'SC0', 'FL_6_DO'),
         new = c('Amazon_Turk_ID', 'Gender', 'Age_Range', 'Education_Level', 'Total_Score', 'Assignment'))

setnames(d_respondents_only, 
         old = c('Q1', 'Q5', 'Q6', 'Q7', 'Q16', 'Q17', 'Q18', 'Q19', 'Q20', 'Q21',
                 'Q8', 'Q9', 'Q10', 'Q11', 'Q22', 'Q23', 'Q24', 'Q25', 'Q26', 'Q27',
                 'Q12', 'Q13', 'Q14', 'Q15', 'Q28', 'Q29', 'Q30', 'Q31', 'Q32', 'Q33'), 
         new = c('Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10',
                 'Q11', 'Q12', 'Q13', 'Q14', 'Q15', 'Q16', 'Q17', 'Q18', 'Q19', 'Q20',
                 'Q21', 'Q22', 'Q23', 'Q24', 'Q25', 'Q26', 'Q27', 'Q28', 'Q29', 'Q30'))

d_respondents_only[ , c("Q1_Score", "Q2_Score", "Q3_Score", "Q4_Score", "Q5_Score",
                        "Q6_Score", "Q7_Score", "Q8_Score", "Q9_Score", "Q10_Score",
                        "Q11_Score", "Q12_Score", "Q13_Score", "Q14_Score", "Q15_Score", 
                        "Q16_Score", "Q17_Score", "Q18_Score", "Q19_Score", "Q20_Score", 
                        "Q21_Score", "Q22_Score", "Q23_Score", "Q24_Score", "Q25_Score", "Q26_Score",
                        "Q27_Score", "Q28_Score", "Q29_Score", "Q30_Score") := 
                      list(ifelse(Q1 == "Normal", 1, 0),
                            ifelse(Q2 == "Normal", 1, 0),
                            ifelse(Q3 == "Pneumonia", 1, 0),
                            ifelse(Q4 == "Pneumonia", 1, 0),
                            ifelse(Q5 == "Normal", 1, 0),
                            ifelse(Q6 == "Pneumonia", 1, 0),
                            ifelse(Q7 == "Pneumonia", 1, 0),
                            ifelse(Q8 == "Normal", 1, 0),
                            ifelse(Q9 == "Pneumonia", 1, 0),
                            ifelse(Q10 == "Normal", 1, 0),
                            ifelse(Q11 == "Pneumonia", 1, 0),
                            ifelse(Q12 == "Normal", 1, 0),
                            ifelse(Q13 == "Pneumonia", 1, 0),
                            ifelse(Q14 == "Pneumonia", 1, 0),
                            ifelse(Q15 == "Normal", 1, 0),
                            ifelse(Q16 == "Normal", 1, 0),
                            ifelse(Q17 == "Pneumonia", 1, 0),
                            ifelse(Q18 == "Normal", 1, 0),
                            ifelse(Q19 == "Pneumonia", 1, 0),
                            ifelse(Q20 == "Normal", 1, 0),
                            ifelse(Q21 == "Normal", 1, 0),
                            ifelse(Q22 == "Normal", 1, 0),
                            ifelse(Q23 == "Pneumonia", 1, 0),
                            ifelse(Q24 == "Normal", 1, 0),
                            ifelse(Q25 == "Pneumonia", 1, 0),
                            ifelse(Q26 == "Pneumonia", 1, 0),
                            ifelse(Q27 == "Pneumonia", 1, 0),
                            ifelse(Q28 == "Pneumonia", 1, 0),
                            ifelse(Q29 == "Normal", 1, 0),
                            ifelse(Q30 == "Normal", 1, 0))]

d_respondents_only[ , Assignment_Group := ifelse(Assignment == "FL_17", "Control", 
                                          ifelse(Assignment == "FL_14", "Self-Reflect",
                                          ifelse(Assignment == "FL_15", "Medical Feedback",
                                          ifelse(Assignment == "FL_16", "Positive Images", "Negative Images"))))]

d_respondents_only[ , c("TaskPhase1_Score", "TaskPhase2_Score", "TaskPhase3_Score") :=
                      list(sum(Q1_Score, Q2_Score, Q3_Score, Q4_Score, Q5_Score, Q6_Score, Q7_Score, Q8_Score, Q9_Score, Q10_Score)/10,
                           sum(Q11_Score, Q12_Score, Q13_Score, Q14_Score, Q15_Score, Q16_Score, Q17_Score, Q18_Score, Q19_Score, Q20_Score)/10,
                           sum(Q21_Score, Q22_Score, Q23_Score, Q24_Score, Q25_Score, Q26_Score, Q27_Score, Q28_Score, Q29_Score, Q30_Score)/10),
                    by = Amazon_Turk_ID]

#head(d_respondents_only)

```


```{r}
# ?register_google
# register_google(key = "AIzaSyCTk2a5vIEqcvgz9KmQmItoNF7J8_hiMMk")
# 
# #uses Google API to obtain location data based on longitude and latitude....dont use unless necessary for new data
# d_respondents_only[ , c("housenumber", "street", "city", "county", "state", "zip", "country") := revgeo(as.numeric(LocationLongitude),as.numeric(LocationLatitude), provider = 'google', API = "AIzaSyCTk2a5vIEqcvgz9KmQmItoNF7J8_hiMMk", output='frame')]
# # 
# head(d_respondents_only)
# # 
# # 
# fwrite(d_respondents_only, file='datatable_clean_survey_responses_v2.dta')

d_respondents <- fread('datatable_clean_survey_responses_v2.dta')

setnames(d_respondents,
         old = c('Duration (in seconds)'),
         new = c('Survey_Duration'))
head(d_respondents)
```

```{r}
nrow(d_respondents)
```

```{r, include=FALSE}
#skip

# ?register_google
# register_google(key = "AIzaSyCTk2a5vIEqcvgz9KmQmItoNF7J8_hiMMk")
# ggmap_show_api_key()
# 
# 
# revgeocode(c(df$lon[1], df$lat[1]))
# 
# d_respondents_only[ Q80 == "A1AC47WJLNW4G7", revgeocode(c(as.numeric(LocationLongitude)[1], as.numeric(LocationLatitude)[1]), output = "address")]
# ?revgeocode
```

```{r}
#remove duplicate Amazon Turk IDs
nrow(d_respondents)  #350 rows
d_respondents <- d_respondents[ !duplicated(d_respondents$Amazon_Turk_ID) , ]  #350 rows
```



# EDA

## Helper Functions
```{r}
create_heatmap <- function(var1, var2) {
  ### Create a heatmap for a table of frequencies between two variables ###
  df <- data.frame(table(var1,var2))
  
  ggplot(df,aes(x=var1,y=var2)) +
    geom_tile(aes(fill=Freq,color=Freq),show.legend=FALSE,alpha=.8) +
    geom_text(aes(label=Freq)) +
    scale_fill_continuous(high = "darkslategray4", low = "powderblue")
}
```

```{r}
#some EDA

#d_respondents[ , table(state, country)]


table(d_respondents$state, d_respondents$country) %>% 
        as.data.frame() %>% 
        arrange(desc(Freq)) %>%
        filter(Freq>0)

table(d_respondents$country) %>% 
        as.data.frame() %>% 
        arrange(desc(Freq))

```

```{r}

table(d_respondents$Total_Score) %>%
  as.data.frame() %>%
  arrange(desc(Var1))

d_respondents %>% 
  group_by(Assignment_Group) %>%
  summarise(mean = mean(Total_Score),
            count = n(),
            time_duration = mean(Survey_Duration))
#d_respondents[ , .(count = .N, avg = mean(Total_Score)), by=Assignment_Group] #same thing

d_respondents[ , hist(Total_Score)]


tapply(d_respondents$Total_Score, d_respondents$Assignment_Group, summary)
tapply(d_respondents$Total_Score, d_respondents$Assignment_Group, sd)
d_respondents[ , sd(Total_Score)]
```

```{r}
library(ggmap)
?register_google
register_google(key = "AIzaSyCTk2a5vIEqcvgz9KmQmItoNF7J8_hiMMk")
# ggmap_show_api_key()

us_map<-get_map(location='united states', zoom=4, maptype = "terrain",
             source='google',color='color')

ggmap(us_map) + geom_point(x=d_respondents$LocationLongitude, y = d_respondents$LocationLatitude, show_guide = TRUE, data = d_respondents, alpha = 0.5, na.rm = T) + scale_color_gradient(low="beige", high="red")

india_map<-get_map(location='india', zoom=5, maptype = "terrain",
             source='google',color='color')

ggmap(india_map) + geom_point(x=d_respondents$LocationLongitude, y = d_respondents$LocationLatitude, show_guide = TRUE, data = d_respondents, alpha = 0.5, na.rm = T) + scale_color_gradient(low="beige", high="red")
```



## Randomization Check
```{r, results='asis'}
#http://www.sthda.com/english/wiki/chi-square-goodness-of-fit-test-in-r

respondent_counts <- d_respondents[ , .(.N), keyby=Assignment_Group]

respondent_counts_chisq_test <- chisq.test(respondent_counts[,2], p=c(1/5, 1/5, 1/5, 1/5, 1/5))

respondent_counts %>% 
  ggplot(aes(x = Assignment_Group,y=N)) + 
  geom_bar(stat = 'identity') +
  coord_flip() +
  xlab('Assignment Group') +
  ylab('Number of Observations') +
  labs(title='Randomization check among assignment groups',
       caption = paste0('Assuming equal distribution among assignment groups, a chi-squared goodness of fit test with ',
                        round(respondent_counts_chisq_test$parameter,4),' degrees of \nfreedom ', 'yields p=',
                        round(respondent_counts_chisq_test$p.value,4),
                        ', suggesting that the observed proportions are not significantly different from the \nexpected proportions at a significance level of 0.05.')) + 
  theme(plot.caption = element_text(hjust = 0))
#p-value = 0.9991, which is greater than significance level of 0.05. 
#We can conclude that the observed proportions are not significantly different from the expected proportions
```

## Covariate Balance Check

```{r}
#let's consider adding age bins and education bins

d_respondents[ Age_Range == "18-24", age_bin := 1]
d_respondents[ Age_Range == "25-34", age_bin := 2]
d_respondents[ Age_Range == "35-44", age_bin := 3]
d_respondents[ Age_Range == "45-54", age_bin := 4]
d_respondents[ Age_Range == "55-64", age_bin := 5]
d_respondents[ Age_Range == "Above 65", age_bin := 6]

d_respondents[ Education_Level == "Associate's degree", edu_bin := 1]
d_respondents[ Education_Level == "Bachelor's degree", edu_bin := 2]
d_respondents[ Education_Level == "High school", edu_bin := 3]
d_respondents[ Education_Level == "Master's degree and above", edu_bin := 4]
d_respondents[ Education_Level == "Some high school", edu_bin := 5]
d_respondents[ Education_Level == "Trade school", edu_bin := 6]

d_respondents[ Assignment_Group == "Control", assign_bin := 1]
d_respondents[ Assignment_Group == "Medical Feedback", assign_bin := 2]
d_respondents[ Assignment_Group == "Negative Images", assign_bin := 3]
d_respondents[ Assignment_Group == "Positive Images", assign_bin := 4]
d_respondents[ Assignment_Group == "Self-Reflect", assign_bin := 5]

d_respondents[ , US_Dummy := ifelse(country == "United States", 1, 0)]

d_respondents[ , Male_Dummy := ifelse(Gender == "Male", 1, 0)]

#add treatment dummy

d_respondents[ , Treatment_Dummy := ifelse(Assignment_Group != "Control", 1, 0)]

#head(d_respondents)



```


```{r}
d_respondents %>% 
  group_by(Assignment_Group) %>%
  summarise(num_respondents = n(),
            pre_treatment_avg = mean(TaskPhase1_Score),
            taskphase2_avg = mean(TaskPhase2_Score),
            taskphase3_avg = mean(TaskPhase3_Score))


d_respondents %>% 
  group_by(Assignment_Group) %>%
  summarise(num_respondents = n(),
            avg_age_bin = mean(age_bin),
            avg_edu_bin = mean(edu_bin),
            male = mean(Male_Dummy),
            US = mean(US_Dummy))

d_respondents %>%
  group_by(Assignment_Group) %>%
  summarise(num_respondents = n(),
            )
```

### Visuals

```{r}
#Density distribution of Survey Duration
ggplot(d_respondents, aes(x=Survey_Duration, colour=as.factor(Assignment_Group), fill = as.factor(Assignment_Group))) + 
  geom_density(alpha = 0.3) + 
  xlim(0, 1500) + 
  xlab("Completion Time (seconds)") +
  ggtitle("Survey Duration Distribution")


#Comparing pretreatment values
ggplot(d_respondents, aes(x=TaskPhase1_Score, fill = as.factor(Treatment_Dummy), colour=as.factor(Treatment_Dummy))) + geom_density(alpha = 0.3)

ggplot(d_respondents, aes(x=TaskPhase1_Score, fill = as.factor(Assignment_Group), colour=as.factor(Assignment_Group))) + geom_density(alpha = 0.3) + ggtitle("PreTreatment Scores by Group") + theme(plot.title = element_text(hjust = 0.5))


#Comparing taskphase2 values
ggplot(d_respondents, aes(x=TaskPhase2_Score, fill = as.factor(Assignment_Group), colour=as.factor(Assignment_Group))) + geom_density(alpha = 0.2) + ggtitle("TaskPhase2 Scores by Group") + theme(plot.title = element_text(hjust = 0.5))

#Comparing taskphase3 values
ggplot(d_respondents, aes(x=TaskPhase3_Score, fill = as.factor(Assignment_Group), colour=as.factor(Assignment_Group))) + geom_density(alpha = 0.2) + ggtitle("TaskPhase3 Scores by Group") + theme(plot.title = element_text(hjust = 0.5))

#boxplots for pretreatment values
ggplot(d_respondents, aes(x = Assignment_Group, y=TaskPhase1_Score, colour=as.factor(Assignment_Group))) + geom_boxplot() + stat_summary(fun.y = mean, geom = "errorbar", aes(ymax = ..y.., ymin = ..y..),
                 width = .75, linetype = "dashed") + ggtitle("PreTreatment Values") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + theme(plot.title = element_text(hjust = 0.5))

#boxplots for TaskPhase2 values
ggplot(d_respondents, aes(x = Treatment_Dummy, y=TaskPhase2_Score, colour=as.factor(Treatment_Dummy))) + geom_boxplot() + stat_summary(fun.y = mean, geom = "errorbar", aes(ymax = ..y.., ymin = ..y..),
                 width = .75, linetype = "dashed") + ggtitle("TaskPhase2 Scores") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + theme(plot.title = element_text(hjust = 0.5))

#boxplots for TaskPhase3 values
ggplot(d_respondents, aes(x = Treatment_Dummy, y=TaskPhase3_Score, colour=as.factor(Treatment_Dummy))) + geom_boxplot() + stat_summary(fun.y = mean, geom = "errorbar", aes(ymax = ..y.., ymin = ..y..),
                 width = .75, linetype = "dashed") + ggtitle("TaskPhase3 Scores") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + theme(plot.title = element_text(hjust = 0.5))


```

#### Gender
```{r fig.width=9}
# TODO format figures and captions
#check balance between gender

gender_chiqq <- chisq.test(d_respondents[ , table(Assignment_Group, Gender)])

create_heatmap(var1 = d_respondents$Assignment_Group,var2 = d_respondents$Gender) +
  xlab('Assignment Group') +
  ylab('Gender') +
  labs(title = 'Contingency table between gender and assignment group',
       caption = paste0('Assuming gender distributions are the same among assignment groups, a chi-squared test for independence with ',
                        round(gender_chiqq$parameter,4),' \ndegrees of freedom ', 'yields p=',
                        round(gender_chiqq$p.value,4),
                        ', suggesting that there is no relationship between gender and assignment groups at a \nsignificance level of 0.05.')) + 
  theme(plot.caption = element_text(hjust = 0))

```

#### Age Range
```{r fig.width=9}
# TODO format figures and captions
#check balance between age-range

# expected frequency count for each cell of the contingency table should be at least 5. Since this is not the case, we set simulate.p.value = TRUE to use Monte Carlo simulation
# https://stats.stackexchange.com/questions/81483/warning-in-r-chi-squared-approximation-may-be-incorrect
age_chisq <- chisq.test(d_respondents[ , table(Assignment_Group, Age_Range)],simulate.p.value = TRUE)

create_heatmap(var1 = d_respondents$Assignment_Group,var2 = d_respondents$Age_Range) +
  xlab('Assignment Group') +
  ylab('Age') +
  labs(title = 'Contingency table between age range and assignment group',
       caption = paste0('Assuming age distributions are the same among assignment groups, a chi-squared test for independence with Monte \nCarlo simulation yields p=',
                        round(age_chisq$p.value,4),
                        ', suggesting that there is no relationship between age and assignment groups at a \nsignificance level of 0.05.')) + 
  theme(plot.caption = element_text(hjust = 0))
```

#### Education Level
```{r fig.width=9}
# TODO format figures and captions
#check balance between education levels
edu_chisq <- chisq.test(d_respondents[ , table(Assignment_Group, Education_Level)],simulate.p.value = TRUE)

create_heatmap(var1 = d_respondents$Assignment_Group,var2 = d_respondents$Education_Level) +
  xlab('Assignment Group') +
  ylab('Education Level') +
  labs(title = 'Contingency table between education and assignment group',
       caption = paste0('Assuming education distributions are the same among assignment groups, a chi-squared test for \nindependence with Monte Carlo simulation yields p=',
                        round(edu_chisq$p.value,4),
                        ', suggesting that there is no relationship \nbetween education and assignment groups at a significance level of 0.05.')) + 
  theme(plot.caption = element_text(hjust = 0))
```

#### Country: US, non-US
```{r fig.width=9}
# TODO format figures and captions
# out.width = "80%"
# check balance between US and non-US respondents

us_chisq <- chisq.test(d_respondents[ , table(Assignment_Group, US_Dummy)])

create_heatmap(var1 = d_respondents$Assignment_Group,var2 = d_respondents$US_Dummy) +
  xlab('Assignment Group') +
  ylab('Country') +
  scale_y_discrete(breaks=c("0", "1"),
                      labels=c("Non-US", "United States")) +
  labs(title = 'Contingency table between country and assignment group',
       caption = paste0('Assuming country distributions are the same among assignment groups, a chi-squared test for independence with \n',
                        round(us_chisq$parameter,4),' degrees of freedom ', 'yields p=',
                        round(us_chisq$p.value,4),
                        ', suggesting that there is no relationship between country and assignment \ngroups at a significance level of 0.05.')) + 
  theme(plot.caption = element_text(hjust = 0))

```


```{r}
# ATE of treatment on Total Score

d_respondents[ Treatment_Dummy == 1, mean(Total_Score)] - d_respondents[ Treatment_Dummy == 0, mean(Total_Score)] 

sd(d_respondents$Total_Score)
```

```{r}
# ATE of treatment on TaskPhase2 Score

d_respondents[ Treatment_Dummy == 1, mean(TaskPhase2_Score)] - d_respondents[ Treatment_Dummy == 0, mean(TaskPhase2_Score)] 

sd(d_respondents$TaskPhase2_Score)

```

```{r}
#trying 2SLS...but dont think it applies here

# d_respondents[ , lm(Total_Score ~ Education_Level)]
# d_respondents[ , ivreg(Total_Score ~ Education_Level | Assignment_Group)]

```

```{r}
power.t.test( delta = .05, sd=.16, sig.level = 0.05, power=0.8)
```

# Analysis

## Helper Functions
```{r}
get_robust_se <- function(model){
  # Get robust SE for use in stargazer
  vcov <- vcovHC(model,type = "HC1")
  return(sqrt(diag(vcov)))
}
```

## Task Phase 2 Analysis
```{r}
# does any treatment have an effect on task phase 2 score?
mod_task2_a <- d_respondents[, lm(TaskPhase2_Score ~ Treatment_Dummy)]

mod_task2_b <- d_respondents[, lm(TaskPhase2_Score ~ Treatment_Dummy + 
                                                     TaskPhase1_Score + 
                                                     as.factor(Gender) + 
                                                     as.factor(Education_Level) + 
                                                     as.factor(Age_Range))]

stargazer(mod_task2_a,
          mod_task2_b,
          se = list(get_robust_se(mod_task2_a),get_robust_se(mod_task2_b)),
          omit = c("Education_Level","Age_Range"),
          add.lines = list(c('Education Fixed Effects', 'No','Yes'),
                           c('Age Fixed Effects','No','Yes')),
          type='text')

#add an F test to compare
anova(mod_task2_a, mod_task2_b, test='F')

#does the specific treatment group have an effect on task phase 2 score?
mod_task2_c <- d_respondents[, lm(TaskPhase2_Score ~ as.factor(Assignment_Group))]

mod_task2_d <- d_respondents[, lm(TaskPhase2_Score ~ as.factor(Assignment_Group) + 
                                                     TaskPhase1_Score + 
                                                     as.factor(Gender) + 
                                                     as.factor(Education_Level) + 
                                                     as.factor(Age_Range))]

# Do you think that there are features of the data that might systematically predict that people will respond strongly or weakly to the treatment effect? List two that you think might be there, in the order that you would like to test them. Then, test for these heterogeneities.
# TODO update this heterogeneity issue. I'm not quite sure this applies because they're both considered treatment groups, just with different granularities
# mod5 <- d_respondents[, lm(TaskPhase2_Score ~ Treatment_Dummy + as.factor(assign_bin) + 
#                              Treatment_Dummy * as.factor(assign_bin))]
stargazer(mod_task2_c,
          mod_task2_d,
          se = list(get_robust_se(mod_task2_c),get_robust_se(mod_task2_d)),
          omit = c("Education_Level","Age_Range"),
          add.lines = list(c('Education Fixed Effects', 'No','Yes'),
                           c('Age Fixed Effects','No','Yes')),
          type='text')

anova(mod_task2_c, mod_task2_d, test='F')
```

## Task Phase 3 Analysis

```{r}
# test final task and any treatment
mod_task3_a <- d_respondents[, lm(TaskPhase3_Score ~ Treatment_Dummy)]
mod_task3_b <- d_respondents[, lm(TaskPhase3_Score ~ Treatment_Dummy + 
                                                     TaskPhase1_Score + 
                                                     as.factor(Gender) + 
                                                     as.factor(Education_Level) + 
                                                     as.factor(Age_Range))]

stargazer(mod_task3_a,
          mod_task3_b,
          se = list(get_robust_se(mod_task3_a),get_robust_se(mod_task3_b)),
          omit = c("Education_Level","Age_Range"),
          add.lines = list(c('Education Fixed Effects', 'No','Yes'),
                           c('Age Fixed Effects','No','Yes')),
          type='text')

anova(mod_task3_a, mod_task3_b, test='F')
```


```{r}
# test final task and specific treatment
mod_task3_c <- d_respondents[, lm(TaskPhase3_Score ~ as.factor(Assignment_Group))]
mod_task3_d <- d_respondents[, lm(TaskPhase3_Score ~ as.factor(Assignment_Group) + 
                                                     TaskPhase1_Score + 
                                                     as.factor(Gender) + 
                                                     as.factor(Education_Level) + 
                                                     as.factor(Age_Range))]

stargazer(mod_task3_c,
          mod_task3_d,
          se = list(get_robust_se(mod_task3_c),get_robust_se(mod_task3_d)),
          omit = c("Education_Level","Age_Range"),
          add.lines = list(c('Education Fixed Effects', 'No','Yes'),
                           c('Age Fixed Effects','No','Yes')),
          type='text')

anova(mod_task3_c, mod_task3_d, test='F')
```

## Wearing Off Effects
```{r,results='asis',message=FALSE}
mod_task3_e <- d_respondents[ , lm(TaskPhase3_Score ~ TaskPhase2_Score)]
mod_task3_f <- d_respondents[ , lm(TaskPhase3_Score ~ TaskPhase2_Score + Treatment_Dummy)]
mod_task3_g <- d_respondents[ , lm(TaskPhase3_Score ~ TaskPhase2_Score + as.factor(Assignment_Group))]
mod_task3_h <- d_respondents[ , lm(TaskPhase3_Score ~ TaskPhase2_Score + 
                                                      as.factor(Assignment_Group) + 
                                                      as.factor(Gender) + 
                                                      as.factor(Education_Level) + 
                                                      as.factor(Age_Range))]

stargazer(mod_task3_e,
          mod_task3_f,
          mod_task3_g,
          mod_task3_h,
          se = list(get_robust_se(mod_task3_e),
                    get_robust_se(mod_task3_f),
                    get_robust_se(mod_task3_h)),
                    get_robust_se(mod_task3_g),
          omit = c("Education_Level","Age_Range"),
          add.lines = list(c('Education Fixed Effects', 'No','No','No','Yes'),
                           c('Age Fixed Effects','No','No','No','Yes')),
          type='html')

anova(mod_task3_e, mod_task3_f, test='F')
anova(mod_task3_g, mod_task3_h, test='F')

```

```{r,results='asis',message=FALSE}
##
mod_task3_i <- d_respondents[ , lm(TaskPhase3_Score ~ TaskPhase1_Score + TaskPhase2_Score)]
mod_task3_j <- d_respondents[ , lm(TaskPhase3_Score ~ TaskPhase1_Score + TaskPhase2_Score + Treatment_Dummy)]
mod_task3_k <- d_respondents[ , lm(TaskPhase3_Score ~ TaskPhase1_Score + TaskPhase2_Score + as.factor(Assignment_Group))]
mod_task3_l <- d_respondents[, lm(TaskPhase3_Score ~ TaskPhase1_Score + TaskPhase2_Score + 
                                                      as.factor(Assignment_Group) + 
                                                      as.factor(Gender) + 
                                                      as.factor(Education_Level) + 
                                                      as.factor(Age_Range))]

stargazer(mod_task3_i,
          mod_task3_j,
          mod_task3_k,
          mod_task3_l,
          se = list(get_robust_se(mod_task3_i),
                    get_robust_se(mod_task3_j),
                    get_robust_se(mod_task3_k),
                    get_robust_se(mod_task3_l)),
          type='html')

anova(mod_task3_i, mod_task3_j, test = 'F')
anova(mod_task3_k, mod_task3_l, test = 'F')

# lm(TaskPhase3_Score ~ TaskPhase2_Score) vs lm(TaskPhase3_Score ~ TaskPhase1_Score + TaskPhase2_Score)
anova(mod_task3_e, mod_task3_i, test = 'F')  
```


## Playground

```{r}
# compare self-reflect against medical feedback groups?
#make dummies
d_respondents[ , Self_Reflect_Dummy := ifelse(Assignment_Group == "Self-Reflect", 1, 0)]
d_respondents[ , Med_Feedback_Dummy := ifelse(Assignment_Group == "Medical Feedback", 1, 0)]

mod_test_dummies1 <- d_respondents[ , lm(TaskPhase2_Score ~ Treatment_Dummy + Self_Reflect_Dummy)]
mod_test_dummies2 <- d_respondents[ , lm(TaskPhase2_Score ~ Treatment_Dummy + Med_Feedback_Dummy)]

stargazer(mod_test_dummies1,
          mod_test_dummies2,
          se = list(get_robust_se(mod_test_dummies1),
                    get_robust_se(mod_test_dummies2)),
          type = 'text')

```

## Playground 2
```{r}

### linear model playground
d_test <- d_respondents[,c("Assignment_Group","TaskPhase1_Score","TaskPhase2_Score","TaskPhase3_Score",'Age_Range',"Education_Level","Gender","Treatment_Dummy")]

#does treatment have an effect on total score?
mod_test1 <- d_test[ , lm(TaskPhase2_Score ~ TaskPhase1_Score + Treatment_Dummy)]


mod_test2 <- d_test[, lm(TaskPhase2_Score ~ TaskPhase1_Score + Treatment_Dummy + (TaskPhase1_Score * Treatment_Dummy))]

#does treatment and pretreatment score have an effect on total score?


###
# seems that if i ad in TaskPhase1 to the linear model, the RSEs disappear...
mod_test3 <- d_test[, lm(TaskPhase2_Score ~  Treatment_Dummy  + 
                                  TaskPhase1_Score +
                                  as.factor(Education_Level) +  
                                  as.factor(Gender) +
                                  as.factor(Age_Range)
                         )]

coeftest(mod_test3, vcov = vcovHC(mod_test3,"HC1"))

summary(d_respondents$TaskPhase1_Score)


stargazer(mod_test1,
          mod_test2,
          mod_test3,
          se = list(get_robust_se(mod_test1),get_robust_se(mod_test2), get_robust_se(mod_test3)),
          type='text')


mod_test4 <- d_test[ , lm(TaskPhase3_Score ~ TaskPhase2_Score)]
coeftest(mod_test4)

# use Robust SE
mod_test2 <- d_respondents[, lm(TaskPhase2_Score ~ Treatment_Dummy  + as.factor(Education_Level) + (Treatment_Dummy * as.factor(Education_Level)))]
mod_test2$vcovHC_ <- vcovHC(mod_test2)
coeftest(mod_test2, vcov = mod_test2$vcovHC_)

```

