---
title: "Feedback MTurk Study"
author: "Dahler Battle, Guy El Khoury, Jane Hung, and Julian Tsang"
date: "15 Dec 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(foreign)
library(data.table)
library(knitr)
library(stargazer)
library(sandwich)
library(car)
library(dplyr)
library(ggmap)
library(revgeo)
library(AER)
library(ggplot2)
library(expss)
library(grid)
library(gridExtra)
library(pander)
```


```{r, include=FALSE}
# clears workspace
rm(list = ls())

# round all numbers to 4 decimals
options(digits=4)

# set theme for ggplot to be cleaner
theme_set(theme_light())
```

# Load Data
```{r, include=FALSE}
# d <- fread('Lungs_November+14,+2020_17.33.csv')
d <- fread('../check-valid-responses/data/qualtrics_results_final.csv')
#head(d)
```
```{r}
d[Q80 %in% c('A2JAMNGL6SDAHQ',	
'A5LYLHG880ABE'	,
'A1IOMFFEKCWOIT',	
'A2JAMNGL6SDAHQ',	
'A1IOMFFEKCWOIT',	
'A5LYLHG880ABE'),]
```

```{r, include=FALSE}
d_respondents_only <-
  d[(Status == "IP Address"),]

# Remove these survey responses because they were from people who did the survey again. Double check that they are removed:
d_respondents_only <-
  d_respondents_only[!ResponseId %in% c(
    'R_1eRkKqfVAmkVzj2',
    'R_3FR03xu5zyOsRSU',
    'R_3HBQsMSMCgXPpKf',
    'R_dbzictBknL9jG3T'
  ), ]

# These WorkerId put in all 1 response (all Normal or all Pneumonia)
d_respondents_only <-
  d_respondents_only[,complier :=ifelse(Q80 %in% c(
    "A119EX2L0DNN1B",
    "A12NQJV6TA5OWB",
    "A18WFPSLFV4FKY",
    "A1BUYK6LXYWMLL",
    "A1FHRZXSE7XNJ4",
    "A1GMYDH5MKN105",
    "A2GSZ3D2XXC533",
    "A2IGIOD74EPOEF",
    "A2J016DRTOBXWO",
    "A2NGFU82LMJ80X",
    "A32K1M0A36EAK5",
    "A371SNJNNUY9Z6",
    "A3BPENSX5EVJ2H",
    "A3EPIT2P3ISA3K",
    "A3NYIJYBHAJ74V",
    "AUFLTHQAXWLH1",
    "AVINXZZV3FNG7" ,
    "A1CD7O60QAQQRT",
    "A1CF1W8CP0DHB0",
    "A1PGY59BR6C5BX",
    "A1YSYI926BBOHW",
    "A1Z3GFH6MNSU46",
    "A211KGJ94WNFLN",
    "A26RPQDD0RQEHL",
    "A2BUHMLNE3LUU0",
    "A2J5BRQ88W745H",
    "A2XIHO2W7EEP32",
    "A3EZ0H07TSDAPW",
    "A3FLBC6LC5GJ3W",
    "A3QLKLIQW1B1FR",
    "A8F6JFG0WSELT",
    "A9K6IVBA0J1CX",
    "ADLZLGHKOAEE6",
    "AE7NJG0KOVZYJ" ,
    "AG5RF4UGQJ7A7" ,
    "AQ9Y6WD8O72ZC" ,
    "tuturtu",
    'A1W05TSPORJPXR',
    'A3SUWCLD1GEGM7',
    'A3A09JB9X1RBXW',
    'A7VQQEIBSM9IU',
    'A8DER1QY96C5X',
    'A1M8MNKK8H5ZGW',
    'A34D5D6PU193AR'
  ),0,1), ]

# These people just gave alternating responses (Normal, Pneumonia, Normal,...,Pneumonia)
# d_respondents_only <- d_respondents_only[!Q80 %in% c(
# 'A1W05TSPORJPXR'
# ,'A3SUWCLD1GEGM7'
# ,'A3A09JB9X1RBXW'
# ,'A7VQQEIBSM9IU'
# ,'A8DER1QY96C5X'
# ,'A1M8MNKK8H5ZGW'
# ,'A34D5D6PU193AR'
# ),]

head(d_respondents_only[,c("Q80",'complier')])
```

```{r, include=FALSE}
#rename task phase questions
setnames(d_respondents_only,
         old = c('Q2', 'Q42'),
         new = c('Self_Reflect_Q1', 'Self_Reflect_Q2'))

setnames(d_respondents_only,
         old = c('Q69', 'Q89'),
         new = c('Control_Q1', 'Control_Q2'))

setnames(d_respondents_only,
         old = c('Q80', 'Q82', 'Q83', 'Q84', 'SC0', 'FL_6_DO'),
         new = c('Amazon_Turk_ID', 'Gender', 'Age_Range', 'Education_Level', 'Total_Score', 'Assignment'))

setnames(d_respondents_only, 
         old = c('Q1', 'Q5', 'Q6', 'Q7', 'Q16', 'Q17', 'Q18', 'Q19', 'Q20', 'Q21',
                 'Q8', 'Q9', 'Q10', 'Q11', 'Q22', 'Q23', 'Q24', 'Q25', 'Q26', 'Q27',
                 'Q12', 'Q13', 'Q14', 'Q15', 'Q28', 'Q29', 'Q30', 'Q31', 'Q32', 'Q33'), 
         new = c('Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10',
                 'Q11', 'Q12', 'Q13', 'Q14', 'Q15', 'Q16', 'Q17', 'Q18', 'Q19', 'Q20',
                 'Q21', 'Q22', 'Q23', 'Q24', 'Q25', 'Q26', 'Q27', 'Q28', 'Q29', 'Q30'))

d_respondents_only[ , c("Q1_Score", "Q2_Score", "Q3_Score", "Q4_Score", "Q5_Score",
                        "Q6_Score", "Q7_Score", "Q8_Score", "Q9_Score", "Q10_Score",
                        "Q11_Score", "Q12_Score", "Q13_Score", "Q14_Score", "Q15_Score", 
                        "Q16_Score", "Q17_Score", "Q18_Score", "Q19_Score", "Q20_Score", 
                        "Q21_Score", "Q22_Score", "Q23_Score", "Q24_Score", "Q25_Score", "Q26_Score",
                        "Q27_Score", "Q28_Score", "Q29_Score", "Q30_Score") := 
                      list(ifelse(Q1 == "Normal", 1, 0),
                            ifelse(Q2 == "Normal", 1, 0),
                            ifelse(Q3 == "Pneumonia", 1, 0),
                            ifelse(Q4 == "Pneumonia", 1, 0),
                            ifelse(Q5 == "Normal", 1, 0),
                            ifelse(Q6 == "Pneumonia", 1, 0),
                            ifelse(Q7 == "Pneumonia", 1, 0),
                            ifelse(Q8 == "Normal", 1, 0),
                            ifelse(Q9 == "Pneumonia", 1, 0),
                            ifelse(Q10 == "Normal", 1, 0),
                            ifelse(Q11 == "Pneumonia", 1, 0),
                            ifelse(Q12 == "Normal", 1, 0),
                            ifelse(Q13 == "Pneumonia", 1, 0),
                            ifelse(Q14 == "Pneumonia", 1, 0),
                            ifelse(Q15 == "Normal", 1, 0),
                            ifelse(Q16 == "Normal", 1, 0),
                            ifelse(Q17 == "Pneumonia", 1, 0),
                            ifelse(Q18 == "Normal", 1, 0),
                            ifelse(Q19 == "Pneumonia", 1, 0),
                            ifelse(Q20 == "Normal", 1, 0),
                            ifelse(Q21 == "Normal", 1, 0),
                            ifelse(Q22 == "Normal", 1, 0),
                            ifelse(Q23 == "Pneumonia", 1, 0),
                            ifelse(Q24 == "Normal", 1, 0),
                            ifelse(Q25 == "Pneumonia", 1, 0),
                            ifelse(Q26 == "Pneumonia", 1, 0),
                            ifelse(Q27 == "Pneumonia", 1, 0),
                            ifelse(Q28 == "Pneumonia", 1, 0),
                            ifelse(Q29 == "Normal", 1, 0),
                            ifelse(Q30 == "Normal", 1, 0))]

d_respondents_only[ , Assignment_Group := ifelse(Assignment == "FL_17", "Control", 
                                          ifelse(Assignment == "FL_14", "Self-Reflect",
                                          ifelse(Assignment == "FL_15", "Medical Feedback",
                                          ifelse(Assignment == "FL_16", "Positive Images", "Negative Images"))))]

d_respondents_only[ , c("TaskPhase1_Score", "TaskPhase2_Score", "TaskPhase3_Score") :=
                      list(sum(Q1_Score, Q2_Score, Q3_Score, Q4_Score, Q5_Score, Q6_Score, Q7_Score, Q8_Score, Q9_Score, Q10_Score)/10,
                           sum(Q11_Score, Q12_Score, Q13_Score, Q14_Score, Q15_Score, Q16_Score, Q17_Score, Q18_Score, Q19_Score, Q20_Score)/10,
                           sum(Q21_Score, Q22_Score, Q23_Score, Q24_Score, Q25_Score, Q26_Score, Q27_Score, Q28_Score, Q29_Score, Q30_Score)/10),
                    by = Amazon_Turk_ID]

d_respondents_only[duplicated(Worker)]

```

```{r}
d_respondents_only[,Treatment_Dummy:= ifelse(Assignment_Group!='Control',1,0)]

compliance_check <- merge(d_respondents_only[,.(total=.N), keyby=Assignment_Group],d_respondents_only[,.(.N), keyby=c("Assignment_Group","complier")],by = "Assignment_Group")
compliance_check[,compliance_rate := N/total]
compliance_check
prop.test(compliance_check[complier==1,N],compliance_check[complier==1,total])
d_respondents_only[,ivreg(TaskPhase2_Score ~ complier, ~Assignment_Group)]

compliance_check <- merge(d_respondents_only[,.(total=.N), keyby=Treatment_Dummy],d_respondents_only[,.(.N), keyby=c("Treatment_Dummy","complier")],by = "Treatment_Dummy")
compliance_check[,compliance_rate := N/total]
compliance_check
prop.test(compliance_check[complier==1,N],compliance_check[complier==1,total])

treatment_dummy_compliance <- d_respondents_only[,ivreg(TaskPhase2_Score ~ complier, ~Treatment_Dummy)]

coeftest(treatment_dummy_compliance,vcov. = vcovHC(treatment_dummy_compliance))

summary(d_respondents_only[,c('TaskPhase2_Score','complier','Treatment_Dummy')])

d_respondents_only[TaskPhase2_Score>1,c('Amazon_Turk_ID','TaskPhase2_Score')]

```

